### ISSUE TITLE
Implement Comment Thread for a book

### ISSUE THREAD

**Issue by NeelMakadiya14** [NeelMakadiya14/Geoup1-Ebook#8]

**Comment by NeelMakadiya14** [comment]
@Jay30801 Please give an updates on this

**Comment by Jay30801** [comment]
Right now , there is no change .Try to check that it is working correctly or not and inform me , if possible.

**Comment by NeelMakadiya14** [comment]
@Jay30801 I have reviewed your commit and mentioned possible errors 
first correct them all and then run it on your local system and if it add commenting, display comment works properly then do PR.

Please do this changes ASAP

**Comment by NeelMakadiya14** [comment]
Implemented by @Jay30801
